# Generated by Django 4.1.3 on 2022-12-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200819_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaluserprofile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical user profile', 'verbose_name_plural': 'historical user profiles'},
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
