# Generated by Django 4.1.3 on 2022-12-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcontactnumber',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical contact number', 'verbose_name_plural': 'historical contact numbers'},
        ),
        migrations.AlterModelOptions(
            name='historicalinstituteaddress',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical institute address', 'verbose_name_plural': 'historical institute addresss'},
        ),
        migrations.AlterModelOptions(
            name='historicalprogram',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical program', 'verbose_name_plural': 'historical programs'},
        ),
        migrations.AlterModelOptions(
            name='historicalsecondaryemail',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical secondary email', 'verbose_name_plural': 'historical secondary emails'},
        ),
        migrations.AlterField(
            model_name='historicalcontactnumber',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalinstituteaddress',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalprogram',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsecondaryemail',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
